/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritence;

import inheritence.Restraunt;

public class Library {

    public void makeingResturant(){
        Restraunt mcDonalds = new Restraunt();
        mcDonalds.name = "McDonalds";
        mcDonalds.price = 2;
        mcDonalds.stars = 3;

        String custRev = "a good place to bring your kids after fencing lessons";

    }
}
