/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void rollTheDiceACertainNumberOfTimes() {
        Library classUnderTest = new Library();

        assertEquals(classUnderTest.roll(5).length, 5);
    }

    @Test void checkForDoubles(){
        Library classTest = new Library();
        int[] dupes = {1,2,4,2,3};
        assertTrue(classTest.containsDuplicates(dupes));
    }

    @Test void averageCalulator(){
        Library classToTest = new Library();
        int[] check = {2,4,6,8};
        int[] check2 = {8,9,8,7,7,10};

        assertEquals(5, classToTest.calculateAverage(check));
        assertEquals(8, classToTest.calculateAverage(check2));
    }

    @Test void smallestArray(){
        Library classToTest = new Library();
         int[][] matrixOne = {
                 {1, 2, 3, 4, 5, 6, 7},
                 {8, 9, 10, 11, 12, 13, 14},
                 {15, 16, 17, 18, 19, 20, 21},
                 {22, 23, 24, 25, 26, 27, 28}
         };

         int[] correct = {1, 2, 3, 4, 5, 6, 7};

         assertEquals(correct, classToTest.matrixSearch(matrixOne));

    }
}
