/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritence;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void addIngPrice() {
        Restraunt sut = new Restraunt();
        String truthy = sut.addPrice(4);
        String expect = "$$$$";
        String many = sut.addPrice(10);

        assertEquals(expect, truthy);
        assertNotEquals("$$$$$", truthy);
        assertEquals("Please enter a number between 0 and 5", many);
    }

    @Test void stringifyResults(){
        Restraunt sut = new Restraunt();
        sut.name = "Mcdonalds";
        sut.stars = 3;
        sut.price = 2;

        String expect = "Mcdonalds Has a rating of 3.0 stars, and has a price rating of $$";

        assertEquals(expect, sut.ToString());
    }

    @Test void makeingAreview(){
        Restraunt sut = new Restraunt();
        sut.name = "Waffle House";
        String comment = "You haven't lived until you've been to a waffle house at 1 am";
        String comment2 = "I herd the cooks getting yelled at then the manager started a fight in the parking lot";

        ArrayList<String> expected = new ArrayList<>();
        expected.add("4 stars - You haven't lived until you've been to a waffle house at 1 am");
        expected.add("1 stars - I herd the cooks getting yelled at then the manager started a fight in the parking lot");


        sut.addReview(4, comment);
        sut.addReview(1, comment2);

        double starExpection = 2.5;

        sut.averageRating();

        assertEquals(expected, sut.comments);
        assertEquals(starExpection, sut.stars);
    }
}
