/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classToTest = new App();

        int[][] checkData ={
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int highTest = 63;
        int lowTest = 62;

        assertEquals(63, classToTest.weatherData(checkData,highTest,lowTest));
    }

    @Test void linterTester() throws IOException {
        App classToTest = new App();
        Path test = Paths.get("tester.js");

        assertEquals("Line 3 is missing semicolon", classToTest.linter(test));

    }
}
